# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b2322ac3da8408683ae1dc283ef821a16b0ac4cfb7061488c42f099b51fd7cb81562d2f99f248621d30956a2622626e0dca413746ab5fc9b4ac5f45349288cfb

test:
  secret_key_base: 1bc73abf38e17dfb0c53407fd65a0da671bde725676db3f36cc94590f6f1f76da9186c2c96e798f5a47f15b2494007e261ebe01e24978b9ef97e81a4bf6243a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
